### ISSUE TITLE
latex error

### ISSUE THREAD

**Issue by susannavergani** [japelj/archival#2]
I get a latex error probably on GWT3 step. 

Here is the output:

```
mela:archival susanna$ python3 archival.py -i input_test.txt 

ARCHIVAL

Input file and content:
	 input_test.txt
		 GWT1	03:55:50.1	-45:06:20	2019-01-06.70
		 GWT2	04:11:34.02	-09:07:21.2
		 GWT3	03:51:59.81	-08:51:18.5
		 GWT4	03:49:55.34	-14:01:55.8
		 GWT5	04:22:17.87	-05:28:05.41
Start program
Note that the execution speed depends on the servers of the pages from where the content is parsed.
GWT1
	Visibility
	... plot saved to: output/GWT1/GWT1.gif
	Extinction
0
	Simbad
	... Search radius:  20  arcsec
	... Number of sources: 0
	TNS
	... Search radius: 20  arcsec
	... Start date: 2001-01-01
	... Number of sources: 0
	GLADE
	... Luminosity distance is not provided - a simple search within a radius of 15 arcsec
	... Number of sources: 0
	Minor planets
	... Search radius: 5  arcmin
	... Magnitude limit: 24.0 mag
	... Epoch: 2019-01-06.70
	... Minor planets found: 0
	Retrieving Pan-STARRS cutout
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=58.95875&dec=-45.105555555555554&size=1200&format=fits&filters=r
|=============================================================================================================|  67 / 67  (100.00%)         0s
	... Image not available
	Retrieving DSS cutout
	... image saved to: output/GWT1/GWT1_dss_red.fits
	Additional info
GWT2
	Visibility
	... plot saved to: output/GWT2/GWT2.gif
	Extinction
0
	Simbad
	... Search radius:  20  arcsec
	... Number of sources:  1
	TNS
	... Search radius: 20  arcsec
	... Start date: 2001-01-01
	... Number of sources: 1
	GLADE
	... Luminosity distance is not provided - a simple search within a radius of 15 arcsec
	... Number of sources: 0
	Minor planets
	Retrieving Pan-STARRS cutout
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=62.89175&dec=-9.122555555555556&size=1200&format=fits&filters=r
|=============================================================================================================| 228 /228  (100.00%)         0s
Downloading https://ps1images.stsci.edu/cgi-bin/fitscut.cgi?ra=62.89175&dec=-9.122555555555556&size=1200&format=fits&red=/rings.v3.skycell/1070/079/rings.v3.skycell.1070.079.stk.r.unconv.fits
|=============================================================================================================| 5.7M/5.7M (100.00%)         1s
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=62.89175&dec=-9.122555555555556&size=240&format=fits&filters=grz
|=============================================================================================================| 550 /550  (100.00%)         0s
	Additional info
GWT3
	Visibility
	... plot saved to: output/GWT3/GWT3.gif
	Extinction
0
	Simbad
	... Search radius:  20  arcsec
	... Number of sources: 0
	TNS
	... Search radius: 20  arcsec
	... Start date: 2001-01-01
	... Number of sources: 0
	GLADE
	... Luminosity distance is not provided - a simple search within a radius of 15 arcsec
	... Number of sources: 0
	Minor planets
	Retrieving Pan-STARRS cutout
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=57.999208333333335&dec=-8.855138888888888&size=1200&format=fits&filters=r
|=============================================================================================================| 233 /233  (100.00%)         0s
Downloading https://ps1images.stsci.edu/cgi-bin/fitscut.cgi?ra=57.999208333333335&dec=-8.855138888888888&size=1200&format=fits&red=/rings.v3.skycell/1068/071/rings.v3.skycell.1068.071.stk.r.unconv.fits
|=============================================================================================================| 5.7M/5.7M (100.00%)         2s
Downloading https://ps1images.stsci.edu/cgi-bin/ps1filenames.py?ra=57.999208333333335&dec=-8.855138888888888&size=240&format=fits&filters=grz
|=============================================================================================================| 565 /565  (100.00%)         0s
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/texmanager.py", line 298, in _run_checked_subprocess
    stderr=subprocess.STDOUT)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['latex', '-interaction=nonstopmode', '--halt-on-error', '/Users/susanna/.matplotlib/tex.cache/e0b7e8056c494eb59f683a341e6d1106.tex']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "archival.py", line 1355, in <module>
    main()
  File "archival.py", line 1333, in main
    pan.append(panscut(lin[0],lin[1],lin[2],fol))
  File "archival.py", line 727, in panscut
    plt.savefig(fol+'/'+name+'/'+fname,dpi=120,format='PNG')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/pyplot.py", line 689, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/figure.py", line 2094, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2075, in print_figure
    **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 510, in print_png
    FigureCanvasAgg.draw(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 402, in draw
    self.figure.draw(self.renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/figure.py", line 1649, in draw
    renderer, self, artists, self.suppressComposite)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 458, in draw
    super().draw(renderer, inframe=inframe)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/artist.py", line 50, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/axes/_base.py", line 2628, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 49, in draw
    self.axes.draw_wcsaxes(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/core.py", line 422, in draw_wcsaxes
    ticks_locs=ticks_locs[coord])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/coordinate_helpers.py", line 558, in _draw_ticks
    tick_out_size=self.ticks.out_size)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/astropy/visualization/wcsaxes/ticklabels.py", line 221, in draw
    bb = super().get_window_extent(renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/text.py", line 930, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/text.py", line 313, in _get_layout
    ismath=ismath)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/backends/backend_agg.py", line 209, in get_text_width_height_descent
    s, fontsize, renderer=self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/texmanager.py", line 464, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/texmanager.py", line 328, in make_dvi
    texfile], tex)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/matplotlib/texmanager.py", line 307, in _run_checked_subprocess
    exc=exc.output.decode('utf-8')))
RuntimeError: latex was not able to process the following string:
b'$$'

Here is the full report generated by latex:
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/MacPorts 2018.47642_8) (preloaded format=latex)
 restricted \write18 enabled.
entering extended mode
(/Users/susanna/.matplotlib/tex.cache/e0b7e8056c494eb59f683a341e6d1106.tex
LaTeX2e <2018-04-01> patch level 2
Babel <3.18> and hyphenation patterns for 25 language(s) loaded.
(/opt/local/share/texmf-texlive/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/opt/local/share/texmf-texlive/tex/latex/base/size10.clo))
(/opt/local/share/texmf-texlive/tex/latex/type1cm/type1cm.sty)
(/opt/local/share/texmf-texlive/tex/latex/base/textcomp.sty
(/opt/local/share/texmf-texlive/tex/latex/base/ts1enc.def
(/opt/local/share/texmf-texlive/tex/latex/base/ts1enc.dfu)))
(/opt/local/share/texmf-texlive/tex/latex/base/inputenc.sty)
(/opt/local/share/texmf-texlive/tex/latex/geometry/geometry.sty
(/opt/local/share/texmf-texlive/tex/latex/graphics/keyval.sty)
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/ifpdf.sty)
(/opt/local/share/texmf-texlive/tex/generic/oberdiek/ifvtex.sty)
(/opt/local/share/texmf-texlive/tex/generic/ifxetex/ifxetex.sty)

Package geometry Warning: Over-specification in `h'-direction.
    `width' (5058.9pt) is ignored.


Package geometry Warning: Over-specification in `v'-direction.
    `height' (5058.9pt) is ignored.

)
No file e0b7e8056c494eb59f683a341e6d1106.aux.
(/opt/local/share/texmf-texlive/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: dvips
! Extra }, or forgotten $.
l.14 \fontsize{10.000000}{12.500000}{\rmfamily $$}
                                                  
No pages of output.
Transcript written on e0b7e8056c494eb59f683a341e6d1106.log.
```
the file ` e0b7e8056c494eb59f683a341e6d1106.tex` contains:

```

\documentclass{article}
\usepackage{type1cm}



\usepackage{textcomp}

\usepackage[utf8]{inputenc}

\usepackage[papersize={72in,72in},body={70in,70in},margin={1in,1in}]{geometry}
\pagestyle{empty}
\begin{document}
\fontsize{10.000000}{12.500000}{\rmfamily $$}
\end{document}
```

**Comment by japelj** [comment]
Hi, should be fixed. Can you please check? 
(the issue was in the new version of astropy, where for particular coordinates the wcs coordinates aren't compatible with "projection" in the matplotlib)

**Comment by susannavergani** [comment]
Perfect! Thanks a lot and sorry for the late replay ;)
